apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

generatorOptions:
  disableNameSuffixHash: true

resources:
- licenses.yaml

configMapGenerator:
- name: tenants-data
  files:
    - sample-data/tenants.json

images:
- name: ghcr.io/thestormforge/sre-interview-exercises-licenses
  newName: ghcr.io/charandas/sre-interview-exercises-licenses
  newTag: 0.0.1
