apiVersion: apps/v1
kind: Deployment
metadata:
  name: scaled-service
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: scaled-service
  template:
    metadata:
      labels:
        app: scaled-service
    spec:
      containers:
      - name: scaled-service
        image: jmalloc/echo-server
        ports:
        - name: http-port
          containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: echo-service
  namespace: default
spec:
  selector:
    app: scaled-service
  ports:
  - name: http-port
    protocol: TCP
    port: 80
    targetPort: http-port
